project_id = "euqgjlnwwviskwnnvsaj"

[functions.upload-to-s3]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.handle-ticket-email-reply]
verify_jwt = false

[functions.generate-smartlink]
verify_jwt = false

[functions.create-release-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.confirm-release-payment]
verify_jwt = false
